[server]
address = "localhost"
port = 8001

# ------------------- Short updates here ------------------- #

[[update]]
content = "might have fixed the timestamps for these :p"
timestamp = 2026-02-07T01:16:53Z

[[update]]
content = "i'm finally adding a little status to here :D"
timestamp = 2025-06-09T20:35:00Z

[[update]]
content = "worker bee building a little website :3"
timestamp = 2025-06-04T20:35:00Z

# ---------------------- Blog posts -------------------------#
[[blog]]
title = "Caltrain AEM-7's"
description = "Idiot sees train"
file = "aem7.md"
image = "aem7.jpg"
tags = ["Trains", "Photography"]
date = 2026-02-09

# --------- All the buttons and blinkies are here! --------- #

[[button]]
file = "kestrel.gif"
alt = "kestrel.pet"
href = "https://kestrel.pet"

[[button]]
file = "lily_pet.gif"
alt = "lily.pet"
href = "https://lily.pet"

[[button]]
file = "bart.gif"
alt = "bay area rapid transit (BART)"
href = "https://bart.gov"

[[button]]
src = "https://badge.les.bi/88x31/bi/trans/half/outset-invert.png"
alt = "bi trans"
href = "https://badge.les.bi"

[[button]]
file = "framework.png"
alt = "framework"
href = "https://frame.work"

[[button]]
file = "firefox.gif"
alt = "firefox"
href = "https://firefox.com"

[[button]]
file = "rtr.png"
alt = "right to repair"

[[button]]
file = "trans.webp"
alt = "transgender"

[[button]]
file = "transrights.png"
alt = "trans rights!"

[[button]]
file = "ebird.png"
alt = "ebird"
href = "https://ebird.org"

[[button]]
file = "paws.png"
alt = "made with my own two paws"

[[button]]
file = "rust.gif"
alt = "rust"

[[button]]
file = "pebber.gif"
alt = "powered by dr pepper"

[[button]]
file = "transit.png"
alt = "transit enthusiast"

[[button]]
file = "femtanyl.png"
alt = "femtanyl"
href = "https://femtanyl.bandcamp.com"

[[button]]
file = "linux.gif"
alt = "made with gnu/linux"

[[button]]
file = "estrogen.gif"
alt = "powered by estrogen"

[[button]]
file = "noai.gif"
alt = "no AI allowed!"

[[blinkie]]
file = "flesh.gif"
alt = "this flesh is a prison"

[[blinkie]]
file = "gender.gif"
alt = "gender is tyranny"

[[blinkie]]
file = "fashion.gif"
alt = "dress like shit"

[[blinkie]]
file = "doggie.gif"
alt = "I love my doggie!"

[[blinkie]]
file = "doggirl.gif"
alt = "doggirl rights!! :3"

[[blinkie]]
file = "birds.gif"
alt = "keeping afloat"

[[blinkie]]
file = "breakcore.gif"
alt = "BREAKCORE!"

[[blinkie]]
file = "pastel.gif"
alt = "pastel lover!"

[[blinkie]]
file = "trains.gif"
alt = "this user is trains"

[[blinkie]]
file = "stars.gif"
alt = "i gaze at stars"
